### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by URL42** [christanaka/circuitpython-bongo#1]
I'm new to this so I appreciate your patience, but how does this react to key input? I don't see the part of the code that drives this. Also should I add in the code to reference the actual OLED screen?

**Comment by URL42** [comment]
Also, I keep getting the following error. Any ideas on how to reconcile?

Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "adafruit_macropad.py", line 252, in __init__
AttributeError: 'module' object has no attribute 'LED'

**Comment by christanaka** [comment]
Hey @holmesha 

> I'm new to this so I appreciate your patience, but how does this react to key input? I don't see the part of the code that drives this. Also should I add in the code to reference the actual OLED screen?

The usage section in the README shows how to set everything up including reacting to keypresses - the reacting is basically just a loop where you are reading key events and passing the key events into `bongo.update()`.

> Also, I keep getting the following error. Any ideas on how to reconcile?
> 
> Traceback (most recent call last): File "", line 9, in File "adafruit_macropad.py", line 252, in **init** AttributeError: 'module' object has no attribute 'LED'

In regards to the error you are getting I'd double check that you have all the required dependencies installed.
